### DISCUSSION TITLE
Distinguishing between a missing property and one set to null

### DISCUSSION THREAD

**Discussion by jamesfcarter** [oapi-codegen/oapi-codegen#1015] [Q&A]
Is there any way of distinguishing between a property that has not been set vs has been set to `null`, eg
```
{
  "name": "missing description"
}
```
vs
```
{
  "name": "null description",
  "description": null
}
```

I was hoping to use a [null string type](https://pkg.go.dev/gopkg.in/guregu/null.v4#String) to achieve this, but as soon as I set the `description` property to be `nullable: true` it converts it into pointer that is nil in both situations. There seems to be a `SkipOptionalPointer` flag that might do what I need, but I don't see any way of setting that. I'm imagining something like this:
```
properties:
  name:
    type: string
  description:
    type: string
    nullable: true
    x-skip-optional-pointer: true
    x-go-type: "null.String"
    x-go-type-import:
      path: "gopkg.in/guregu/null.v4"
```

Is there any way of achieving this?

Thanks.
