### DISCUSSION TITLE
import-mapping vs additional-imports confusion

### DISCUSSION THREAD

**Discussion by NyteMode** [oapi-codegen/oapi-codegen#1311] [Q&A]
I'm currently working with the 'petstore-expanded' spec, since I'm new to oapi-codegen. Here's my project structure at the moment:

```
├──petstore-expanded.yaml
└──pet/
```

For my use case, I'm needing certain types to be defined within other packages (such as the `pet` package above). I originally followed what [the readme mentions](https://github.com/deepmap/oapi-codegen/tree/master#import-mappings) about this, but with this generator config file instead of just command arguments:

```yaml
package: main
generate:
  gin-server: true
import-mapping:
  ./pet/spec.yaml: pet
output: petstore.gen.go
```

You'll notice I'm not using a full path like `abc.com/path/to/package`. I haven't published my project anywhere yet, so assuming a relative path like mine isn't valid, I guess my first question is: Why is there a reliance on a full path? Regardless, constructing that generator config file based on the guidelines [in this part of the readme](https://github.com/deepmap/oapi-codegen/tree/master#using-oapi-codegen) led me to [cmd/oapi-codegen/oapi-codegen.go](https://github.com/deepmap/oapi-codegen/blob/master/cmd/oapi-codegen/oapi-codegen.go#L48), and then I noticed that import-mapping is deprecated. I couldn't make sense of the "new format" that's mentioned in that deprecation comment, so if someone could provide an example of that, I'd appreciate it. 

Anyway, while searching for the replacement of import-mapping, I ran into [this comment](https://github.com/deepmap/oapi-codegen/pull/389#issuecomment-1243080859) on another thread (and many other threads referencing said comment), so I decided to try that method out, and replaced `import-mapping` with `additional-imports`, so that my top-level generator config looked like this

```yaml
package: main
generate:
  gin-server: true
additional-imports:
  - alias: . 
    package: pet
output: petstore.gen.go
```

And at this point my directory tree looked like this:

```
├──petstore-expanded.yaml
├──petstore.cfg.yaml
└──pet/
   ├──spec.yaml
   └──pet.cfg.yaml
```

where `petstore-expanded.yaml` contains

```yaml
...
components:
  schemas:
    Container:
      properties:
        Pet:
          $ref: ./pet/spec.yaml#/components/schemas/Pet
        NewPet:
          $ref: ./pet/spec.yaml#/components/schemas/NewPet
        Error:
          $ref: ./pet/spec.yaml#/components/schemas/Error
```

after moving the schemas to `pet/spec.yaml`, it contains

```yaml
components:
  schemas:
    Pet:
      ...

    NewPet:
      ...

    Error:
      ...
```

and my generator config inside the `pet` package contains

```yaml
package: pet
generate:
  models: true
output: pet/pet.gen.go
```

But when I execute `oapi-codegen -config petstore.cfg.yaml petstore-expanded.yaml` I get the error:

```error loading swagger spec : map key "NewPet" not found```

where the key it highlights could be any of the types defined in `pet/spec.yaml` (i.e., `NewPet` or `Pet` or `Error`).

I'm sure I've messed things up, by trying both methods. Whatever the correct way forward is, if I could get some guidance on how to separate certain types into their respective packages, I would greatly appreciate it!
