### DISCUSSION TITLE
Does oapi-codegen support openapi string's regex patterns?

### DISCUSSION THREAD

**Discussion by fasolens** [oapi-codegen/oapi-codegen#1714] [Q&A] [answered]
Hi,
I haven't found answer for this question nowhere. I've added string pattern to openapi spec, and it is not generated anywhere. Is it some kind of bug, or it is not supported?

```yaml
    MacAddress:
      description: Mac Address
      type: object
      properties:
        macAddress:
          type: string
          pattern: "$[0-9a-fA-F]{12}$"
          example: "0bae5d905866"
      required:
        - macAddress
```
