### DISCUSSION TITLE
How can i generate models with types like duration and Decimal?

### DISCUSSION THREAD

**Discussion by Alpensin** [oapi-codegen/oapi-codegen#1896] [Q&A]
I got model in openapi with such properties:
```yaml
schemas:
  CustomScheme:
    properties:
      virtualAmount:
        type: number
        format: decimal
      requestTimeout:
        type: string
        format: duration
```

Please show me how can i make custom template for them?
I suppose I can use github.com/shopspring/decimal for decimal
