### DISCUSSION TITLE
OneOf/AnyOf for required properties

### DISCUSSION THREAD

**Discussion by lzap** [oapi-codegen/oapi-codegen#1943] [General]
Hey,

everytime I have a schema with only required fields being part of `oneOf/anyOf`:

```yaml
---
type: object
properties:
  services:
    type: array
    items:
      type: object
      oneOf:
      - title: firewall_service
        required:
        - service
      - title: firewall_port
        required:
        - port
      - title: firewall_from_to
        required:
        - from
        - to
      properties:
        from:
          type: integer
          maximum: 65535
          minimum: 1
        port:
          type: integer
          maximum: 65535
          minimum: 1
        protocol:
          default: any
          type: string
          enum:
          - tcp
          - udp
          - any
        service:
          type: string
          minLength: 2
        to:
          type: integer
          maximum: 65535
          minimum: 1
      additionalProperties: false
    nullable: true
additionalProperties: false
```

the generator creates union types.

```go
type BlueprintNetworkFirewallServicesProtocol string

type BlueprintNetworkFirewallServices0 = interface{}
type BlueprintNetworkFirewallServices1 = interface{}
type BlueprintNetworkFirewallServices2 = interface{}

type Blueprint_Network_Firewall_Services_Item struct {
	From     *int                                      `json:"from,omitempty"`
	Port     *int                                      `json:"port,omitempty"`
	Protocol *BlueprintNetworkFirewallServicesProtocol `json:"protocol,omitempty"`
	Service  *string                                   `json:"service,omitempty"`
	To       *int                                      `json:"to,omitempty"`
	union    json.RawMessage
}

func (t Blueprint_Network_Firewall_Services_Item) AsBlueprintNetworkFirewallServices0() (BlueprintNetworkFirewallServices0, error) {
	var body BlueprintNetworkFirewallServices0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *Blueprint_Network_Firewall_Services_Item) FromBlueprintNetworkFirewallServices0(v BlueprintNetworkFirewallServices0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t *Blueprint_Network_Firewall_Services_Item) MergeBlueprintNetworkFirewallServices0(v BlueprintNetworkFirewallServices0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}
```

Despite there is any data in them. Is there a workaround? Can I stop the generator from creating those types? Thanks.
