### DISCUSSION TITLE
Define to output file names for types and server

### DISCUSSION THREAD

**Discussion by devinpapalangi** [oapi-codegen/oapi-codegen#1958] [Q&A] [answered]
Hi!

I am new to this "way of development" and to this package. I am trying to implement import mapping here and i ran into some issues in generating both the types and the server using `cfg.yaml`

some basic information:
1. Go Version: 1.23.5
2. oapi-codegen version: v2.4.1
3. Device: Macbook Pro M1

I haven't found a way to configure both the `types` and `server` code generation in the `cfg-masters.yaml`

```yaml
# yaml-language-server: $schema=../../../configuration-schema.json
package: masters
output: ../../../src/domain/masters/gen/openapi_http.gen.go
generate:
  models: true
  gin-server: true
output-options:
  skip-prune: true
import-mapping:
  ../base/base.yaml: ssa-backend/api/openapi/base/base.yaml
```

Code above run just fine, but is there anyway to generate two separate file for the `types` and `server`? Currently it generates both in one file `openapi_http.gen.go`. I am trying to generate two file `openapi_types.gen.go` and `openapi_http.gen.go` just for SoC (Separation of Concern).

I haven't found any information about this.

**I Tried to**
```yaml
# yaml-language-server: $schema=../../../configuration-schema.json
package: masters
output: ../../../src/domain/masters/gen/openapi_http.gen.go
output-models: ../../../src/domain/masters/gen/openapi_types.gen.go
generate:
  models: true
  gin-server: true
output-options:
  skip-prune: true
import-mapping:
  ../base/base.yaml: ssa-backend/api/openapi/base/base.yaml
```

And you can guess that it doesn't work, because that key is basically my own imagination.

Any help? Thanks in advance
