### DISCUSSION TITLE
multiple spec files

### DISCUSSION THREAD

**Discussion by bogdan-dubyk** [oapi-codegen/oapi-codegen#770] [Q&A]
hey, first of all I think there is a very big possibility that it's very straightforward to solve my issue, as I'm a noob in GO, but I have a `yaml` spec files (will share below) from which I can generate code with usage of https://openapi-generator.tech/ go library but not able to do so with deepmap. 

So basically I have such `yaml` files:
`api.yaml`
```
openapi: 3.0.0
info:
  title: OpenAPI Library Demo App
  version: 0.0.1
servers: [
  {
    "url": "http://localhost:8000",
    "description": "local development server",
  },
]
paths:
  /users:
    post:
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "user.yaml#/components/schemas/registerUser"
      responses:
        "200":
          description: create a new user
        "400":
          description: bad request, bad data
        "409":
          description: conflict
```

and `user.yaml`

```
components:
  parameters:
    firstName:
      name: firstName
      in: query
      description: user first name
      schema:
        type: string
    lastName:
      name: lastName
      in: query
      description: user last name
      schema:
        type: string
    email:
      name: email
      in: query
      description: user email
      schema:
        type: string
    password:
      name: password
      in: query
      description: user password
      schema:
        type: string
    accountType:
      name: accountType
      in: query
      description: account type
      schema:
        type: string
        enum: ["candidate", "employer"]
  schemas:
    registerUser:
      type: object
      title: User registration
      properties:
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
        email:
          type: string
          description: user email name
          format: email
          example: user@example.com
        password:
          type: string
          description: user password
        accountType:
          type: string
          enum: [ "candidate", "employer" ]
          description: account type
    required:
      - firstName
      - lastName
      - email
      - password
      - accountType
```

and my generated `config.yaml` is:

```
package: user
generate:
  chi-server: true
  models: true
target: src/api
```

and when I'm running `oapi-codegen --config config.yaml  api.yaml ` I'm getting error `:error loading swagger spec in api/openapi/specs/api.yaml
: error resolving reference "user.yaml#/components/schemas/registerUser": error unmarshaling JSON: failed to unmarshal property "components" (*openapi3.Components): failed to unmarshal property "schemas" (*openapi3.Schemas): failed to unmarshal extension properties: json: cannot unmarshal array into Go value of type map[string]json.RawMessage (["firstName","lastName","email","password","accountType"])` 

And if I'm changing ` $ref: "user.yaml#/components/schemas/registerUser"` into  ` $ref: "user.yaml` in `api.yaml`, it generating server code but without `registerUser` model.

And identically same yaml specification generating correct code with usage of https://openapi-generator.tech/ . What I'm  doing wrong?
