### DISCUSSION TITLE
Response body constructor

### DISCUSSION THREAD

**Discussion by ssyrota** [oapi-codegen/oapi-codegen#783] [Q&A]
Hey-hey!

Is it possible to generate a constructor for the response body?

Currently my config generates only body structs without a constructor:
```
package: server
generate:
  echo-server: true
  strict-server: true
  embedded-spec: true
  models: true
output: ./src/web/server/server.gen.go
```

It would be nice to have something like:
```
// Creates fine
type Schema struct {
	Column string     `json:"column"`
	Type   SchemaType `json:"type"`
}

// Proposal function
func NewSchema(column string, type string) (*Schema, error){...}
```
