### ISSUE TITLE
incorrect fill params with date type

### ISSUE THREAD

**Issue by apopov-app** [oapi-codegen/oapi-codegen#104]
Hello, i found bug again :)

If i use url parameter with "format: date" it generate model code:
```
Date *openapi_types.Date `json:"date,omitempty"`
```

this code in middleware:
```
err = runtime.BindQueryParameter("form", true, false, "date", r.URL.Query(), &params.Date)
```
	
I think the reflex inside runtime.BindQueryParameter determines that this is a structure and tries to fill the field "as a structure". 

As a result, to fill out this type, you must complete the request:
localhost/pets?Time=2006-01-02T15:04:05.999999999Z&limit=111 
(*openapi_types.Date contains inside time.Time)

instead
localhost/pets?date=2019-10-01&limit=111

Swagger example:
```
     parameters:
        - name: date
          in: query
          description: test date
          required: false
          schema:
            type: string
            format: date
```

Demo project: https://github.com/ruelephant/petstore
