### ISSUE TITLE
Property required doesn't work for Struct params

### ISSUE THREAD

**Issue by ZhiqiangWang0** [oapi-codegen/oapi-codegen#1044]
1. set `required` for a query param

```
        - name: "startDate"
          in: query
          required: true
          schema:
            type: string
            format: date
            example: 2022-09-06
```

2. server code generated

```
err = runtime.BindQueryParameter("form", true, true, "startDate", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}
```

3. `required` isn't validated for Struct like other cases
https://github.com/deepmap/oapi-codegen/blob/29ebe3262399dbbf9d9ce612757e50cd2ec2862f/pkg/runtime/bindparam.go#LL349C3-L349C3

```
			case reflect.Struct:
				// This case is really annoying, and error prone, but the
				// form style object binding doesn't tell us which arguments
				// in the query string correspond to the object's fields. We'll
				// try to bind field by field.
				var fieldsPresent bool
				fieldsPresent, err = bindParamsToExplodedObject(paramName, queryParams, output)
				// If no fields were set, and there is no error, we will not fall
				// through to assign the destination.
				if !fieldsPresent {
					return nil
				}
```

It seems not reasonable.
