### ISSUE TITLE
`x-go-type-import`: clarify when need to use and validate extensions

### ISSUE THREAD

**Issue by Antonboom** [oapi-codegen/oapi-codegen#1114]
Hello!

Maybe it's better to split it into two issues, I don't know :)

### Problem statement

Long time we have the next spec:

```yml
  parameters:
    XRequestIDHeader:
      in: header
      name: X-Request-ID
      schema:
        type: string
        format: uuid
        x-go-type: types.RequestID       
        x-go-import:                                 # Typo! Right is `x-go-type-import`
          path: "github.com/some-awesome-service/internal/types"
      required: true
```

And did not notice the typo `x-go-import`.

Why did it work? Because we were surprised to find that the tool itself [adds the necessary imports](https://github.com/deepmap/oapi-codegen/blob/ad62d73d8d22aa251d06b490b259790919899eab/pkg/codegen/codegen.go#L358) (thanks to the `golang.org/x/tools/imports`) and it is not necessary to specify them.

### Proposal

1) Add extension validation code. For example, it would be great to see an error like `unknown extension 'x-go-import'`.
2) Add documentation about `x-go-type-import` – when it is really needed and when it can be omitted.

Thanks 🙂
