### ISSUE TITLE
Confused about usage of additionalProperties in a schema

### ISSUE THREAD

**Issue by falzm** [oapi-codegen/oapi-codegen#128]
Hi,

I'm a bit confused about the usage of `additionalProperties` [to create a dictionary/map as described in the Swagger doc](https://swagger.io/docs/specification/data-models/dictionaries/). Despite reading the README, I don't understand how a spec such as:

```yaml
components:
  schemas:
    MyResource:
      properties:
        created:
          format: date-time
          readOnly: true
          type: string
        description:
          type: string
        id:
          format: uuid
          readOnly: true
          type: string
        name:
          type: string
        tags:
          additionalProperties:
            type: string
          type: object
      type: object
```

results in:

```go
// MyResource defines model for MyResource.
type MyResource struct {
    Created     *time.Time              `json:"created,omitempty"`
    Description *string                 `json:"description,omitempty"`
    Id          *string                 `json:"id,omitempty"`
    Name        *string                 `json:"name,omitempty"`
    Tags        *MyResource_Tags        `json:"tags,omitempty"`
}

// MyResource_Tags defines model for MyResource.Tags.
type MyResource_Tags struct {
    AdditionalProperties map[string]string `json:"-"`
}
```

instead of

```go
// MyResource defines model for MyResource.
type MyResource struct {
    Created     *time.Time              `json:"created,omitempty"`
    Description *string                 `json:"description,omitempty"`
    Id          *string                 `json:"id,omitempty"`
    Name        *string                 `json:"name,omitempty"`
    Tags        map[string]string       `json:"tags,omitempty"`
}
```

Am I doing something wrong?
