### ISSUE TITLE
OR semantics for scopes of same security scheme

### ISSUE THREAD

**Issue by ugurzongur** [oapi-codegen/oapi-codegen#1347]
With the current code generation for scopes, it's clunky to get OR semantics for the same security scheme. E.g. In order to get `("Admin") OR ("User" and "ExampleCapable")`, I intend to use:
```
paths:
  /example:
    get:
      security:
        - bearerAuth: ["Admin"]
        - bearerAuth: ["User", "ExampleCapable"]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```
But this results in the following code:
```
c.Set(BearerAuthScopes, []string{"Admin"})
c.Set(BearerAuthScopes, []string{"User", "ExampleCapable"})
```
Where the last one overrides the previous undesirably. The above code is for gin but the pattern is same for all as far as I see.

Ideally the generated code should be something like:
```
c.Set(BearerAuthScopes, [][]string{{"Admin"}, {"User", "ExampleCapable"}})
```

However this is backwards incompatible, so another possible solution is providing raw security scopes in another context variable. E.g.:
```
c.Set("OpenAPI.Security", []map[string][]string{
		{"bearerAuth": {"Admin"}},
		{"bearerAuth": {"User", "ExampleCapable"}},
	})
```

There is a workaround which is to have multiple security schemes like bearerAuth0, bearerAuth1..etc. but that's not ideal.
