### ISSUE TITLE
Handling of default values

### ISSUE THREAD

**Issue by tschaub** [oapi-codegen/oapi-codegen#138]
It looks to me like the `default` values for parameters (perhaps also for other struct fields) are not being applied.  For example, here is a `limit` parameter with a default of `250` that might be used for an operation that lists large collections:

```yaml
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 0
            maximum: 1000
            default: 250
```

Since parameter validation is currently the job of [middleware](https://github.com/deepmap/oapi-codegen/blob/master/pkg/middleware/oapi_validate.go), should handling the default also be left to the middleware?
