### ISSUE TITLE
Implement maxProperties and minProperties for additionalProperties

### ISSUE THREAD

**Issue by maks56893** [oapi-codegen/oapi-codegen#1523]
It would be great if it became possible to check the number of fields in additional properties by scheme like this:
```
field_name:
          type: object
          additionalProperties:
            maxProperties: 1
            type: string
```
