### ISSUE TITLE
Generating *interface{} in additionalProperties

### ISSUE THREAD

**Issue by maks56893** [oapi-codegen/oapi-codegen#1683]
If I want to accept nullable fields in additionalProperties I need to use nullable. But if I want just gen map[string]interafe{} with nullable I get map[string]*interface{}. It's at least will be inconvenient

Example schema:
```
 TestFields:
      type: object
      required: ["fields"]
      properties:
        fields:
          type: object
          additionalProperties:
            nullable: true
```
