### ISSUE TITLE
Import Mappings not referencing correct variables.

### ISSUE THREAD

**Issue by MUzairS15** [oapi-codegen/oapi-codegen#1685]
```
package: core
generate:
  models: true
output-options:
  skip-prune: true
  name-normalizer: ToCamelCase
  initialism-overrides: true
  disable-type-aliases-for-type:
    - array
output: core/core.go
```
The `core.go` file is generated using the above config and is the base file which contains all core types.

Other OpenAPI spec needs to reference the type declared in `core.go`. Below is the config file for generating the go code for other dependent specs.

```
package: a
generate:
  models: true
output-options:
  # NOTE that this is only required for the `Unreferenced` type
  skip-prune: true
  name-normalizer: ToCamelCase
  initialism-overrides: true
  disable-type-aliases-for-type:
    - array
import-mapping:
  ./core.yml: github.com/meshery/schemas/models/core
output: v1alpha2/a.go
```

Snippet of generated `core.go` file
```
/ Emails defines model for emails.
type Emails []Email

// ID defines model for id.
type ID = uuid.UUID

// MapObject defines model for map_object.
type MapObject map[string]string

// NullTime SQL null Timestamp to handle null values of time.
type NullTime = sql.NullTime

// OperationID defines model for operation_id.
type OperationID = uuid.UUID
```

Snippet of generated `a.go` file
```

import (
	externalRef0 "github.com/muzairs15/models/core"
)

// ConnectionId defines model for connectionId.
type ConnectionId = externalRef0.Id

// CredentialId defines model for credentialId.
type UserId = externalRef0.Id
```
The generated file uses the import mapping but fails to correctly utilise/de-referenced the variable names.
Instead of referencing as `externalRef0.ID` it is using `externalRef0.Id`.

Also, how can I give a name to the imports? eg: Instead of `externalRef0` using `core` as the import name.

**Comment by jamietanna** [comment]
Just to confirm, what version of `oapi-codegen` are you using?

**Comment by jamietanna** [comment]
> Also, how can I give a name to the imports? eg: Instead of externalRef0 using core as the import name.

That's not possible right now due to how we generate that - feel free to raise another feature request for this!

**Comment by MUzairS15** [comment]
```
oapi-codegen -version                                                                                                                          
github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
v2.3.0
```

**Comment by MUzairS15** [comment]
> > Also, how can I give a name to the imports? eg: Instead of externalRef0 using core as the import name.
> 
> That's not possible right now due to how we generate that - feel free to raise another feature request for this!

👍🏻

**Comment by MUzairS15** [comment]
Any suggestion to fix this @jamietanna

**Comment by mromaszewicz** [comment]
This is a comment from an automated bug scrub, after making a significant number of fixes to the code generation.

We reproduced the two-package import-mapping setup against the current `main`, and the casing now matches (so it compiles).

**Core spec** (`core.yaml`): schemas `ID` (`format: uuid`) and `Email`, generated with `name-normalizer: ToCamelCaseWithInitialisms` + `skip-prune`.

**Dependent spec** (`a.yaml`):
```yaml
components:
  schemas:
    ConnectionId:
      $ref: './core.yaml#/components/schemas/ID'
```
**Dependent config** (`a-config.yaml`):
```yaml
package: a
output: v1alpha2/a.go
generate:
  models: true
output-options:
  skip-prune: true
  name-normalizer: ToCamelCaseWithInitialisms
import-mapping:
  ./core.yaml: github.com/example/models/core
```

**Result:** the initialism-aware normalizer emits `type ID` in core, and the dependent package now references it with matching case:
```go
// core.go
type ID = openapi_types.UUID
// a.go
type ConnectionID = externalRef0.ID   // was: externalRef0.Id (undefined)
```
Generating both packages and running `go build ./...` across them **succeeds** — the wrong-casing `externalRef0.Id` reference is gone.

Additionally, the external-ref package alias is now customizable, if you'd rather not have the auto-generated `externalRef0`. Put an alias in front of the path in the mapping value (space-separated):
```yaml
import-mapping:
  ./core.yaml: "core github.com/example/models/core"
```
which produces `core "github.com/example/models/core"` and references like `type ConnectionID = core.ID`.

(Side note: the `initialism-overrides: true` key in your original config isn't a valid option; the equivalent today is `name-normalizer: ToCamelCaseWithInitialisms`.) Closing as fixed.
