### ISSUE TITLE
error generating code: error formatting Go code -> expected operand, found '<' (and 10 more errors)

### ISSUE THREAD

**Issue by mat813** [oapi-codegen/oapi-codegen#1736]
I am trying to generate the code for [netbox](https://github.com/netbox-community/netbox), and it has a few schemas like this :

```yaml
components:
  schemas:
    ConsolePort:
      type: object
        speed:
          type: object
          properties:
            value:
              enum:
              - 1200
              - 2400
              - 4800
              - 9600
              - 19200
              - 38400
              - 57600
              - 115200
              - null
              type: integer
              description: |-
                * `1200` - 1200 bps
                * `2400` - 2400 bps
                * `4800` - 4800 bps
                * `9600` - 9600 bps
                * `19200` - 19.2 kbps
                * `38400` - 38.4 kbps
                * `57600` - 57.6 kbps
                * `115200` - 115.2 kbps
            label:
              type: string
              enum:
              - 1200 bps
              - 2400 bps
              - 4800 bps
              - 9600 bps
              - 19.2 kbps
              - 38.4 kbps
              - 57.6 kbps
              - 115.2 kbps
          nullable: true
```

where the values list has a null in it, and the generated code is:

```go
// Defines values for ConsolePortSpeedValue.
const (

  ConsolePortSpeedValueN115200 ConsolePortSpeedValue = 115200
  ConsolePortSpeedValueN1200 ConsolePortSpeedValue = 1200
  ConsolePortSpeedValueN19200 ConsolePortSpeedValue = 19200
  ConsolePortSpeedValueN2400 ConsolePortSpeedValue = 2400
  ConsolePortSpeedValueN38400 ConsolePortSpeedValue = 38400
  ConsolePortSpeedValueN4800 ConsolePortSpeedValue = 4800
  ConsolePortSpeedValueN57600 ConsolePortSpeedValue = 57600
  ConsolePortSpeedValueN9600 ConsolePortSpeedValue = 9600
  ConsolePortSpeedValueNil ConsolePortSpeedValue = <nil>
)
```

Note the `<nil>` last value. I figure it should be simply `nil`.
