### ISSUE TITLE
Issue generating enum values defined in the query param

### ISSUE THREAD

**Issue by phiHero** [oapi-codegen/oapi-codegen#1760]
Similar to #603

Generate correctly when enum values is a flow-style sequence 

```yaml
/example:
    get:
      parameters:
        - in: query
          name: enum_query
          schema:
            type: string
            enum: [asc, desc]
```

But does not work when specifying one enum value per line (block-style sequence)

```yaml
enum: 
 - asc
 - desc
```
oapi-codegen `v2.3.0`
openapi `3.0.3`
