### ISSUE TITLE
error parsing config file

### ISSUE THREAD

**Issue by FedeBev** [oapi-codegen/oapi-codegen#1826]
I'm using `github.com/oapi-codegen/oapi-codegen/v2 v2.4.1` and I've defined the following config

```yaml
package: api
generate:
  iris-server: true
  models: true
  embedded-spec: true
output: api.gen.go
```
but when I run the generate command I get the following error

```
error parsing config file: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into []string
```

What am I missing?
