### ISSUE TITLE
Query Parameter Array Format Not Properly Generated

### ISSUE THREAD

**Issue by ludoviclaffineur** [oapi-codegen/oapi-codegen#1837]
### Description
The generator currently doesn't properly handle array query parameters when generating Gin server code. When an OpenAPI spec defines an array query parameter, the generated code doesn't include the `[]` suffix in the parameter name, which is required for proper array parameter binding in Gin.

### Current Behavior
For array query parameters, the generator produces code like:
```go
if paramValue := c.Query("document-types")
err = runtime.BindQueryParameter("form", true, true, "document-types", ...)
```

### Expected Behavior
Array query parameters should include the `[]` suffix:

```go
if paramValue := c.Query("document-types[]")
err = runtime.BindQueryParameter("form", true, true, "document-types[]", ...)
```

### Impact
This issue affects the handling of array query parameters in generated Gin server code. Without the `[]` suffix, the server cannot properly bind array parameters from the request URL.

### Possible Solution
Modify the server code template to append `[]` to query parameter names when the parameter is defined as an array type in the OpenAPI specification.

### Additional Context
This is particularly important for proper array parameter binding in Gin, which expects the `[]` suffix for array parameters in the query string (e.g., `?document-types[]=value1&document-types[]=value2`).

```yml
      - name: document-types
          in: query
          description: Filter documents by type
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid
```
