### ISSUE TITLE
Multiple content types collide in generated request body type definition

### ISSUE THREAD

**Issue by kylesower** [oapi-codegen/oapi-codegen#1858]
First off, I'd like to say thank you very much for this project. It's saved me many hours!

oapi-codegen version used: main branch
go version used: go1.22.0 darwin/arm64

When a request body includes multiple media/content types that aren't specified in the function `GenerateBodyDefinitions`, they all get created under the corresponding struct with the field name `Body`, thus creating invalid code. It would be helpful to have them all labeled like the JSONBody, TextBody, etc. are labeled. As a specific example:
```yml openapi.yml
openapi: "3.0.0"
paths:
  /files:
    post:
      operationId: addFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
          image/png:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
          text/html:
            schema:
              type: string
              format: binary
```

```yml server-codegen.yml
package: api
generate:
  gorilla-server: true
  strict-server: true
  embedded-spec: true
  models: true
output: server.gen.go
```
The broken output struct in `server.gen.go`:
```go
type AddFileRequestObject struct {
	JSONBody *AddFileJSONRequestBody
	Body     io.Reader
	Body     io.Reader
	Body     io.Reader
}
```
One workaround is to delete the extra `Body` fields and add the request headers to the context with a middleware to determine how to process the body. However, the broken code needs to be deleted every time. It would be nice if the output was more like this:
```go
type AddFileRequestObject struct {
	JSONBody *AddFileJSONRequestBody
	JPEGBody *AddFileJPEGRequestBody
	PNGBody  *AddFilePNGRequestBody
	HTMLBody *AddFileHTMLRequestBody
}
```
This would allow processing the request in a strict server without an additional middleware.

However, if the server generated output like above, it would be a breaking change. Someone relying on the Body field in the generated API for a single content type (e.g. image/png) would have the name changed out from under them. Therefore, perhaps it would be better to also include the body, as follows:
```go
type AddFileRequestObject struct {
	JSONBody *AddFileJSONRequestBody
	JPEGBody *AddFileJPEGRequestBody
	PNGBody  *AddFilePNGRequestBody
	HTMLBody *AddFileHTMLRequestBody
        Body io.Reader
}
```
I'd be happy to contribute a fix depending on what the maintainers would like. Thank you!

**Comment by alsiberij** [comment]
+1

I think that one of the possible solutions is to add custom key to yaml spec, as well as update its parser. This setting should override deafult name `Body`. For example
```yaml
image/jpeg:
    schema:
        type: string
        format: binary
        x-strict-body-key: JPEGBoby
text/html:
    schema:
        type: string
        format: binary
         x-strict-body-key: HTMLBody
```
