### ISSUE TITLE
Support of multiple yaml content in one file

### ISSUE THREAD

**Issue by jakofys** [oapi-codegen/oapi-codegen#1863]
I really like to have a single configuration file instead of defined multiple file as shown in [this example](https://github.com/oapi-codegen/oapi-codegen/tree/main?tab=readme-ov-file#using-multiple-packages-with-one-openapi-spec-per-package).

Use a separator as file limit and implements it using v2 yaml library (already used) to avoid inheritance behaviour as shown in [stack overflow topic](https://stackoverflow.com/questions/53464099/read-multiple-yamls-in-a-file).

```yaml
package: app
output: server.gen.go
generate:
  std-http-server: true
---
package: app
output: types.gen.go
generate:
  model: true
```
