### ISSUE TITLE
AdditionalProperties values does not use nullable.Nullable type

### ISSUE THREAD

**Issue by nikbanerjee-unity** [oapi-codegen/oapi-codegen#1875]
I have a config that uses nullable types:

```
output-options:
  nullable-type: true
```

Say I then use additional properties, example schema:

```
  schemas:
    MySchema:
      properties:
        data:
          type: object
          additionalProperties:
            type: string
            nullable: true
```

I would assume this would generate a type for data of:

```
Data *map[string]nullable.Nullable[string] `json:"data,omitempty"`
```

.. but instead it generates:

```
Data *map[string]string `json:"data,omitempty"`
```

I've confirmed setting `nullable: true` in other properties works fine in my spec, so it seems limited to its use in additionalProperties. Am I missing something, or should the behaviour be different? Thanks!
