### ISSUE TITLE
Support generating struct field accessor methods

### ISSUE THREAD

**Issue by 0xch4z** [oapi-codegen/oapi-codegen#1949]
Support generating `GetXXXXX` accessor methods for structs. Either by default or by output option. This would make it easy to build interfaces around common fields for generated structs.

Go's protobuf generator does this for all `message` generated structs [here](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/protoc-gen-go/generator/generator.go#L1805). ([example](https://github.com/grpc/grpc-go/blob/732f3f32f5365f4f5b89a3f1be19534cd28db794/examples/helloworld/helloworld/helloworld.pb.go#L121 ))

With the following schema:

```yaml
components:
  schemas:
    Server:
      type: object
      properties:
        metro:
          type: string
        # ...
    Drive:
      type: object
      properties:
        metro:
          type: string
        # ...
      required:
        - name
```

These would be generated as:

```golang
type Server struct {
        Metro string `json:"metro"`
        // ...
}

func (s *Server) GetMetro() string {
       return s.Metro
}

type Drive struct {
        Metro string `json:"metro"`
        // ...
}

func (d *Drive) GetMetro() string {
       return d.Metro
}
```

So the user could do something like:

```golang
// Abstract type fulfilled by generated structs with `metro: {type: string}`
type LocalizedResource interface {
        GetMetro() string
}

var (
        // The generated structs implement LocalizedResource.
        _ LocalizedResource = (nil)(*Server)
        _ LocalizedResource = (nil)(*Drive)
)
```
