### ISSUE TITLE
Can't pass security validation when using oapi validation middleware

### ISSUE THREAD

**Issue by bandirsen** [oapi-codegen/oapi-codegen#221]
I use this library on sever side, while on client side do manually since the client is for mobile platform.

This is my openapi spec :
I follow [openapi documentation](https://swagger.io/docs/specification/authentication/bearer-authentication/) to define security scheme
```
paths:
  /admins:
    get:
      description: Get AdminList
      security:
        - bearerAuth: []
      operationId: getAdminList
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

And in my request I put Authorization header on request
`Authorization: Bearer ---random JWT token ----`

But I always get 'Security requirements failed' from validation middleware (the JWT token was checked and valid)
Am I missing something ?

PS: also it return http error 403, while above documentation recommending to return http 401 error for unauthorized request.

**Comment by zaccari** [comment]
I'm seeing this error as well, with the global `security` set (not at the path level):

```yaml
paths:
  /models:
    post:
    ...
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
```

Removing the global `security` lets the validation pass:

```bash
curl -X POST "http://127.0.0.1:8090/models" -H "Authorization: Bearer a503faf9-45b5-4fec-8334-337284a66ea4" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"name\":\"string\",\"type\":\"string\",\"options\":\"string\",\"parentId\":\"string\"}"
```

I'm looking into the issue now, just wanted to make a note of it here for reference
