### ISSUE TITLE
Custom struct fieldname 

### ISSUE THREAD

**Issue by octomad** [oapi-codegen/oapi-codegen#468]
This is a feature request to support custom struct field names.

We have a situation where we are using `allOf` to reference a JSON schema that has a property with a similar name. After the name gets sanitized for Go, it ends up duplicating a field name that already exists.

Example:

**parentschema.json**
```json
{
  "title": "node",
  "type": "object",
  "description": "Represents a node",
  "properties": {
    "@id": {
      "type": "string",
      "readOnly": true
    }
}
```

**components in the OpenAPI Spec**
```yaml
components:
  schemas:
    resourcenode:
      title: resourcenode
      allOf:
        - $ref: ./parentschema.json
        - type: object
          properties:
            id:
              type: string
              format: uuid
              description: ID of the resource
              readOnly: true
```

Because there's a property in the parentschema.json called `@id`, and a property in the OpenAPI schema called `id`, the generated code will output

```go
type Resourcenode struct {
	Id string `json:"@id"`
	Id string `json:"id"`
}
```

Which obviously won't compile because of the duplicate field in the struct. If we could add support for custom field names, that would help.

An alternative approach would be to add an X-Extension for `x-go-fieldname-prefix` to prefix the property so that it generates this instead

```go
type Resourcenode struct {
	NodeId string `json:"@id"`
	Id string `json:"id"`
}
```
