### ISSUE TITLE
Wrong type for not required slice

### ISSUE THREAD

**Issue by icecube092** [oapi-codegen/oapi-codegen#469]
This swagger code

```
genres:

          type: array

          uniqueItems: true

          items:

            type: integer
```

generates this fields

`Genres *[]int `json:"genres,omitempty"``

Slice already is a pointer, so this field must not be a pointer to slice. If field not required, just set a tag. This problem on all types slices.
I think map has the same problem. Maps is a pointers too and fields must not be a pointer to map.
