### ISSUE TITLE
Panic invalid port with Server Variable Object

### ISSUE THREAD

**Issue by PlusMinus0** [oapi-codegen/oapi-codegen#575]
According to [this](https://spec.openapis.org/oas/v3.0.3#server-object-example) the following should be a legal spec:

```yaml
servers:
  - url: http://localhost:{port}/v1
    description: The local test server
    variables:
      port:
        default: '8080'
```
however, the oapi validate middleware throws an error:

```
panic: parse "http://localhost:--------------------------------------------------port__________________________________________________/v1": invalid port ":--------------------------------------------------port__________________________________________________" after host

github.com/deepmap/oapi-codegen/pkg/middleware.OapiRequestValidatorWithOptions(0xaf7600?, 0x0)
	/home/matthias/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.10.1/pkg/middleware/oapi_validate.go:72 +0xf9
github.com/deepmap/oapi-codegen/pkg/middleware.OapiRequestValidator(...)
	/home/matthias/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.10.1/pkg/middleware/oapi_validate.go:56
```
